name: arch
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  flutter_html: ^3.0.0-beta.2
  equatable: ^2.0.5
  provider: ^6.0.5
  collection: ^1.16.0
  intl: ^0.19.0
  loader_overlay: ^2.2.0
  shared_preferences: ^2.1.2
  permission_handler: ^10.3.0
  get_it: ^7.6.0
  stack_trace: ^1.11.0
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.9
  flutter_multi_formatter: ^2.11.7
  validators: ^3.0.0
  flutter_blurhash: ^0.8.2
  url_launcher: ^6.2.4
  camera: ^0.10.5+9
 # flutter_datetime_picker: ^1.5.1

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  file_picker: ^6.1.1
  dotted_border: ^2.1.0

flutter_intl:
  enabled: true
  main_locale: ru
  arb_dir: lib/shared/l10n/arb
  output_dir: lib/shared/l10n/generated

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Light.otf
        

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: lib/core/_shared/assets/fonts/inter/Inter-Regular.ttf
  #         weight: 400
  #       - asset: lib/core/_shared/assets/fonts/inter/Inter-Medium.ttf
  #         weight: 500
  #       - asset: lib/core/_shared/assets/fonts/inter/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: lib/core/_shared/assets/fonts/inter/Inter-Bold.ttf
  #         weight: 700
  #   - family: Montserrat Alternates
  #     fonts:
  #       - asset: lib/core/_shared/assets/fonts/montserrat_alternates/MontserratAlternates-Bold.ttf
  #         weight: 700
  #   - family: Montserrat
  #     fonts:
  #       - asset: lib/core/_shared/assets/fonts/montserrat/Montserrat-Regular.ttf
  #         weight: 400
  #       - asset: lib/core/_shared/assets/fonts/montserrat/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: lib/core/_shared/assets/fonts/montserrat/Montserrat-SemiBold.ttf
  #         weight: 600
  #       - asset: lib/core/_shared/assets/fonts/montserrat/Montserrat-Bold.ttf
  #         weight: 700
  #   - family: Montserrat Alternates
  #     fonts:
  #       - asset: lib/core/_shared/assets/fonts/montserrat_alternates/MontserratAlternates-Bold.ttf
  #         weight: 700
  #   - family: SF Pro Text
  #     fonts:
  #       - asset: lib/core/_shared/assets/fonts/sf_pro_text/SF-Pro-Text-Semibold.otf
  #         weight: 600
  #   - family: SF Pro Text
  #     fonts:
  #       - asset: lib/core/_shared/assets/fonts/sf_pro_text/SF-Pro-Text-Semibold.otf
  #         weight: 600